In [10]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

## 5 random tensor and shuffle it!

1

In [3]:
np.random.randint(low=0, high=10, size=(3,3))

array([[1, 6, 2],
       [5, 6, 0],
       [4, 0, 2]])

In [18]:
tensor_1 = tf.constant([
    [1, 6, 2],
    [5, 6, 0],
    [4, 0, 2]])
shuffled_tensor_1 = tf.random.shuffle(tensor_1)
shuffled_tensor_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 0, 2],
       [5, 6, 0],
       [1, 6, 2]], dtype=int32)>