In [38]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.11.0'

## 🌱 seed <br>
Ada 2 macam jenis seed: <br>
1. global level
2. operation level

### 🌎 global level
contoh

In [99]:
tf.random.set_seed(1)# Operation level
rand_num = tf.random.normal(shape=(3,2))
shuffle_num = rand_num
tf.random.shuffle(shuffle_num) # Operation level 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.2246722 , -0.9811211 ],
       [ 0.383644  , -0.87965786],
       [-1.1012203 ,  1.5457517 ]], dtype=float32)>

### operation level

In [103]:
rand_num = tf.random.Generator.from_seed(42)
rand_num = rand_num.normal(shape=(3,2))
shuffle_num = rand_num
tf.random.shuffle(shuffle_num)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

## tf.constant
build on top np.array()

In [4]:
tf.constant(7)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
vector = tf.constant([
    [1,2,3],
    [4,5,6],
])
vector.shape

TensorShape([2, 3])

In [23]:
#3 * 2 * 4 <br>
#3 karena tanda kurung warna biru ada 3 <br>
#2 karena disetiap tanda kurung warna biru, ada 2 tanda kurung <br>
#4 karena disetiap tanda kurung warna kuning ada 4 angka <br>
vector = tf.constant([
    [[1,2,3,4],[4,5,6,7]],
    [[7,8,9,0],[10,11,12,1]],
    [[1,2,3,4],[4,5,6,8]]
], dtype ="float16")
vector.shape

TensorShape([3, 2, 4])

## tf.Variable
tf variable bisa re_assign, tf constant tidak <br>
<br>
🔑 <b>Note:</b> if u unsure whether use constant or variable, just use constant 

In [13]:
tf_variable = tf.Variable([10,7])
tf_constant = tf.constant([10,7])

In [21]:
tf_variable[0].assign(69)
tf_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([69,  7], dtype=int32)>

In [24]:
# error karena constant tidak bisa di reassignt
#tf_constant[0].assign(69)

## tf.random
FYI : tf initialize random tensor before learning the data

In [25]:
rand_num = tf.random.Generator.from_seed(42)
rand_num = rand_num.normal(shape=(3,2))
rand_num

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

## 🔀 tf.random.shuffle
FYI: the order of the data impact model

In [37]:
shuffle_num = rand_num
tf.random.shuffle(shuffle_num, 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>